name: Update submodules

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-workflow
  cancel-in-progress: false

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Pull and update submodules
    steps:
      - name: Checkout contents repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DWARVES_PAT }}
          submodules: recursive
          fetch-depth: 1

      - name: Commit and push changes
        uses: ./.github/actions/git-commit-push
        with:
          commit-message: 'chore(ci): reindex'
